from __future__ import annotations

import json
import tempfile
import zipfile
from pathlib import Path
from typing import Any

import shapefile
from pyproj import Transformer
from shapely.geometry import mapping, shape
from shapely.ops import transform

from spatial_common import BAY_AREA_COUNTIES, PROJECT_ROOT, sha256_file, update_metadata


DEFAULT_ACS_PATH = PROJECT_ROOT / "data" / "processed" / "bay-area-acs-2023.json"
DEFAULT_TRACT_ZIP = PROJECT_ROOT / "data" / "raw" / "cb_2023_us_tract_500k.zip"
DEFAULT_WATER_TRACTS = PROJECT_ROOT / "data" / "raw" / "acs2023-bay-area-water-tracts.geojson"
TRACT_SOURCE_URL = "https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_tract_500k.zip"
WATER_SOURCE_URL = "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_ACS2023/MapServer/8"
ACS_SOURCE = "Generated by data/scripts/prepare_acs.py from U.S. Census Bureau ACS 2023 5-year tables"
SCRIPT_VERSION = "2.1.0"
APPROVED_WATER_GEOIDS = frozenset({
    "06001990000", "06013990000", "06041990100", "06075990100",
    "06075990200", "06081990100", "06097990100",
})
DEFAULT_NDJSON_PATH = PROJECT_ROOT / "data" / "processed" / "bay-area-tracts.ndjson"
DEFAULT_GEOJSON_PATH = PROJECT_ROOT / "web" / "public" / "data" / "bay-area-tract-density.geojson"


def normalize_acs_geoid(value: str) -> str:
    prefix = "1400000US"
    normalized = value[len(prefix) :] if value.startswith(prefix) else value
    if len(normalized) != 11 or not normalized.isdigit():
        raise ValueError(f"Invalid tract GEOID: {value!r}")
    return normalized


def _load_acs(path: Path) -> tuple[int, dict[str, dict[str, Any]]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    year = int(payload["metadata"]["year"])
    records: dict[str, dict[str, Any]] = {}
    for record in payload["records"]:
        geoid = normalize_acs_geoid(str(record["geoid"]))
        if geoid in records:
            raise ValueError(f"Duplicate ACS GEOID: {geoid}")
        if record.get("population") is None:
            raise ValueError(f"Missing population for GEOID: {geoid}")
        records[geoid] = record
    return year, records


def build_population_products(
    acs_path: Path,
    tract_zip_path: Path,
    ndjson_path: Path,
    geojson_path: Path,
    water_tracts_path: Path | None = None,
    *,
    expected_water_geoids: set[str] | frozenset[str] = frozenset(),
    expected_total: int | None = None,
) -> int:
    acs_year, acs_records = _load_acs(acs_path)
    transformer = Transformer.from_crs("EPSG:4269", "EPSG:4326", always_xy=True)
    seen_geoids: set[str] = set()
    rows: list[dict[str, Any]] = []
    features: list[dict[str, Any]] = []

    with tempfile.TemporaryDirectory(prefix="homeorbit-tracts-") as temp_dir:
        with zipfile.ZipFile(tract_zip_path) as archive:
            archive.extractall(temp_dir)
        shapefiles = list(Path(temp_dir).rglob("*.shp"))
        if len(shapefiles) != 1:
            raise ValueError(f"Expected one shapefile in {tract_zip_path}, found {len(shapefiles)}")
        with shapefile.Reader(str(shapefiles[0])) as reader:
            field_names = [field[0] for field in reader.fields[1:]]
            required = {"STATEFP", "COUNTYFP", "GEOID", "ALAND"}
            missing_fields = required - set(field_names)
            if missing_fields:
                raise ValueError(f"Missing shapefile fields: {sorted(missing_fields)}")

            for shape_record in reader.iterShapeRecords():
                attributes = dict(zip(field_names, shape_record.record))
                state_fips = str(attributes["STATEFP"])
                county_fips = str(attributes["COUNTYFP"])
                if state_fips != "06" or county_fips not in BAY_AREA_COUNTIES:
                    continue
                geoid = str(attributes["GEOID"])
                if geoid in seen_geoids:
                    raise ValueError(f"Duplicate shapefile GEOID: {geoid}")
                seen_geoids.add(geoid)
                acs = acs_records.get(geoid)
                if acs is None:
                    raise ValueError(f"No ACS record for shapefile GEOID: {geoid}")
                aland_m2 = int(attributes["ALAND"])
                if aland_m2 <= 0:
                    raise ValueError(f"Non-positive ALAND for GEOID: {geoid}")
                population = int(acs["population"])
                density = population / (aland_m2 / 1_000_000)
                geometry = transform(transformer.transform, shape(shape_record.shape.__geo_interface__))
                row = {
                    **acs,
                    "geoid": geoid,
                    "aland_m2": aland_m2,
                    "population_density_km2": density,
                    "geometry": mapping(geometry),
                }
                rows.append(row)
                properties = {
                    "geoid": geoid,
                    "county_name": acs.get("county_name", BAY_AREA_COUNTIES[county_fips]),
                    "population": population,
                    "population_density_km2": density,
                    "acs_year": acs_year,
                }
                features.append(
                    {
                        "type": "Feature",
                        "properties": properties,
                        "geometry": mapping(geometry.simplify(0.0001, preserve_topology=True)),
                    }
                )

    if water_tracts_path is not None:
        water_payload = json.loads(water_tracts_path.read_text(encoding="utf-8"))
        if water_payload.get("type") != "FeatureCollection":
            raise ValueError("Supplemental water tracts must be a FeatureCollection")
        actual_water_geoids = {str(feature["properties"]["GEOID"]) for feature in water_payload["features"]}
        if len(water_payload["features"]) != len(expected_water_geoids) or actual_water_geoids != set(expected_water_geoids):
            raise ValueError("Supplemental features do not match approved water tract GEOIDs")
        for feature in water_payload["features"]:
            properties = feature["properties"]
            geoid = str(properties["GEOID"])
            if geoid in seen_geoids:
                raise ValueError(f"Duplicate supplemental GEOID: {geoid}")
            acs = acs_records.get(geoid)
            if acs is None:
                raise ValueError(f"No ACS record for supplemental GEOID: {geoid}")
            if (
                geoid[:2] != "06" or geoid[2:5] not in BAY_AREA_COUNTIES or not geoid[5:].startswith("99")
                or str(properties["STATE"]) != geoid[:2] or str(properties["COUNTY"]) != geoid[2:5]
                or int(properties["AREALAND"]) != 0 or int(properties["AREAWATER"]) <= 0
                or int(acs["population"]) != 0
            ):
                raise ValueError(f"Invalid water tract attributes for GEOID: {geoid}")
            seen_geoids.add(geoid)
            geometry = shape(feature["geometry"])
            row = {**acs, "geoid": geoid, "aland_m2": 0, "population_density_km2": None, "geometry": mapping(geometry)}
            rows.append(row)
            feature_properties = {
                "geoid": geoid,
                "county_name": acs["county_name"],
                "population": 0,
                "population_density_km2": None,
                "acs_year": acs_year,
            }
            features.append({"type": "Feature", "properties": feature_properties, "geometry": mapping(geometry.simplify(0.0001, preserve_topology=True))})

    unmatched = set(acs_records) - seen_geoids
    if unmatched:
        sample = ", ".join(sorted(unmatched)[:5])
        raise ValueError(f"ACS GEOIDs not linked to shapefile ({len(unmatched)}): {sample}")
    if expected_total is not None and len(rows) != expected_total:
        raise ValueError(f"Expected {expected_total} tracts, found {len(rows)}")

    ndjson_path.parent.mkdir(parents=True, exist_ok=True)
    with ndjson_path.open("w", encoding="utf-8", newline="\n") as output:
        for row in rows:
            output.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
    geojson_path.parent.mkdir(parents=True, exist_ok=True)
    geojson_path.write_text(
        json.dumps({"type": "FeatureCollection", "features": features}, ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    if ndjson_path.resolve().is_relative_to(PROJECT_ROOT):
        source = {
            "url": TRACT_SOURCE_URL,
            "path": tract_zip_path.resolve().relative_to(PROJECT_ROOT).as_posix(),
            "size_bytes": tract_zip_path.stat().st_size,
            "sha256": sha256_file(tract_zip_path),
        }
        inputs = {"cartographic_boundaries": source}
        if water_tracts_path is not None:
            inputs["water_tracts"] = {
                "url": WATER_SOURCE_URL,
                "path": water_tracts_path.resolve().relative_to(PROJECT_ROOT).as_posix(),
                "size_bytes": water_tracts_path.stat().st_size,
                "sha256": sha256_file(water_tracts_path),
                "record_count": len(json.loads(water_tracts_path.read_text(encoding="utf-8"))["features"]),
            }
        inputs["acs"] = {
            "path": acs_path.resolve().relative_to(PROJECT_ROOT).as_posix(), "source": ACS_SOURCE,
            "year": acs_year, "size_bytes": acs_path.stat().st_size, "sha256": sha256_file(acs_path),
        }
        update_metadata(
            "tracts", ndjson_path, len(rows), acs_year=acs_year, inputs=inputs,
            script_version=SCRIPT_VERSION,
            parameters={"state_fips": "06", "county_fips": sorted(BAY_AREA_COUNTIES),
                        "simplify_tolerance": 0.0001, "expected_total": expected_total,
                        "expected_water_geoids": sorted(expected_water_geoids)},
        )
    if geojson_path.resolve().is_relative_to(PROJECT_ROOT):
        bounds = [shape(feature["geometry"]).bounds for feature in features]
        spatial_extent = [
            min(item[0] for item in bounds), min(item[1] for item in bounds),
            max(item[2] for item in bounds), max(item[3] for item in bounds),
        ]
        update_metadata(
            "tract_density_geojson", geojson_path, len(features), acs_year=acs_year,
            derived_from={"product": "tracts", "path": ndjson_path.resolve().relative_to(PROJECT_ROOT).as_posix(),
                          "sha256": sha256_file(ndjson_path)},
            script_version=SCRIPT_VERSION, simplify_tolerance=0.0001,
            spatial_extent=spatial_extent,
        )
    return len(rows)


def main() -> None:
    count = build_population_products(
        DEFAULT_ACS_PATH,
        DEFAULT_TRACT_ZIP,
        DEFAULT_NDJSON_PATH,
        DEFAULT_GEOJSON_PATH,
        DEFAULT_WATER_TRACTS,
        expected_water_geoids=APPROVED_WATER_GEOIDS,
        expected_total=1772,
    )
    print(f"Wrote {count} Bay Area census tracts")


if __name__ == "__main__":
    main()
